!!python/object:config.GenConfig {BATCH_SIZE: 64, EMB_DIM: 32, HIDDEN_DIM: 32, PRE_EPOCH_NUM: 350,
  SEED: 88, SEQ_LENGTH: 20, START_TOKEN: 0, TRAIN_ITER: 1}
!!python/object:config.DisConfig
DIS_12_REG_LAMBDA: 0.2
DIS_ALTER_EPOCH: 50
DIS_BATCH_SIZE: 64
DIS_DROPOUT_KEEP_PROB: 0.75
DIS_EMBEDDING_DIM: 64
DIS_FILTER_SIZES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20]
DIS_NUM_EPOCHS: 3
DIS_NUM_FILTERS: [100, 200, 200, 200, 200, 100, 100, 100, 100, 100, 160, 160]
10
...
